name: Scheduled Cypress Tests

on:
  schedule:
    # Runs at 12:00am UTC every day (see https://crontab.guru)
    - cron: '0 0 * * *'
jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.5.0-chrome94-ff93
    steps:
      - uses: actions/checkout@v3
      - name: input node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: npm
      - name: install depedencies
        run: npm ci --ignore-scripts
      - name: run ui / integration (no backend integration) tests
        run: npm run test:components
