name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.5.0-chrome94-ff93
    strategy:
      fail-fast: false
      matrix:
        containers: [1,2,3,4]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v3
      # this is needed because of weird issues with the container we are using
      - run: chown -R 1001:1001 /github/home/.cache && echo "pwn dat cache"
      - name: Run Component Tests
        uses: cypress-io/github-action@v4
        with:
          parallel: true
          install: false
          options: --user 1001
          browser: chrome
          component: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
