name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.5.0-chrome94-ff93
#    strategy:
#      fail-fast: false
#      matrix:
#        containers: [1,2,3,4,5]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: GitHub Action for Yarn
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
#        with:
#          cmd: install --immutable
#      - run: npx cypress install
#      - run: yarn test:unit
